spring:
  application:
    name: movie-reservation-system

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_reservation_db
    username: postgres
    password: Password
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update # Don't auto-create tables, use Flyway instead
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  # Flyway Migration Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false # Be careful with this in production

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration
logging:
  level:
    com.ishan.moviereservation: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# JWT Configuration
jwt:
  secret: your-super-secret-jwt-key-make-it-very-long-and-secure-in-production-environment
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# Application-specific Configuration
app:
  reservation:
    hold-duration: 900000 # 15 minutes in milliseconds
